# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1122, 662)
        Form.setStyleSheet("#Form {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(81, 167, 172, 255), stop:0.60199 rgba(146, 100, 169, 255), stop:1 rgba(146, 72, 239, 255));\n"
"}\n"
"")
        self.camera_place_label = QtWidgets.QLabel(Form)
        self.camera_place_label.setGeometry(QtCore.QRect(83, 100, 478, 462))
        self.camera_place_label.setStyleSheet("QLabel{\n"
"    border:1px solid rgba(0,0,0,0.3);\n"
"    background-color: rgb(146, 146, 182);\n"
"}\n"
"")
        self.camera_place_label.setText("")
        self.camera_place_label.setObjectName("camera_place_label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(629, 180, 451, 221))
        self.label_2.setStyleSheet("QLabel{\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    background-color:rgba(255,255,255,0.2);\n"
"}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.email_lineedit = QtWidgets.QLineEdit(Form)
        self.email_lineedit.setGeometry(QtCore.QRect(715, 230, 341, 50))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.email_lineedit.setFont(font)
        self.email_lineedit.setStyleSheet("QLineEdit{\n"
"    border:1px solid transparent;\n"
"    border-radius:25px;\n"
"    background-color: rgba(112, 11, 239, 0.3);\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgba(0,0,0,0.5);\n"
"    border-radius:25px;\n"
"    background-color: rgba(112, 11, 239, 0.3);\n"
"}")
        self.email_lineedit.setText("")
        self.email_lineedit.setFrame(True)
        self.email_lineedit.setAlignment(QtCore.Qt.AlignCenter) #type: ignore 
        self.email_lineedit.setDragEnabled(False)
        self.email_lineedit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)#type: ignore 
        self.email_lineedit.setClearButtonEnabled(False)
        self.email_lineedit.setObjectName("email_lineedit")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(660, 235, 41, 41))
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/email.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(90, 572, 47, 47))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/icons/user.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(660, 300, 41, 41))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/icons/padlock.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pass_lineedit = QtWidgets.QLineEdit(Form)
        self.pass_lineedit.setGeometry(QtCore.QRect(715, 300, 341, 50))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pass_lineedit.setFont(font)
        self.pass_lineedit.setStyleSheet("QLineEdit{\n"
"    border:1px solid transparent;\n"
"    border-radius:25px;\n"
"    background-color: rgba(112, 11, 239, 0.3);\n"
"}\n"
"QLineEdit:hover{\n"
"    border:1px solid rgba(0,0,0,0.5);\n"
"    border-radius:25px;\n"
"    background-color: rgba(112, 11, 239, 0.3);\n"
"}")
        self.pass_lineedit.setText("")
        self.pass_lineedit.setFrame(True)
        self.pass_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_lineedit.setAlignment(QtCore.Qt.AlignCenter)#type: ignore 
        self.pass_lineedit.setDragEnabled(False)
        self.pass_lineedit.setObjectName("pass_lineedit")
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setGeometry(QtCore.QRect(640, 410, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))#type: ignore 
        self.login_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(112, 11, 239);\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:  rgb(112, 11, 239) ;\n"
"    color:white;\n"
"    border:1px solid rgba(0,0,0,0.3);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(66, 6, 144);\n"
"    color:white;\n"
"    border:1px solid rgba(0,0,0,0.3);\n"
"    border-radius:20px;\n"
"}")
        self.login_button.setObjectName("login_button")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(83, 100, 5, 70))
        self.line.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line.setLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(83, 100, 70, 5))
        self.line_2.setStyleSheet("background-color:black;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(490, 558, 70, 5))
        self.line_3.setStyleSheet("background-color:black;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(555, 490, 5, 70))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_4.setLineWidth(0)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(555, 100, 5, 70))
        self.line_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_5.setLineWidth(0)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Form)
        self.line_6.setGeometry(QtCore.QRect(490, 100, 70, 5))
        self.line_6.setStyleSheet("background-color:black;")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Form)
        self.line_7.setGeometry(QtCore.QRect(83, 558, 70, 5))
        self.line_7.setStyleSheet("background-color:black;")
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Form)
        self.line_8.setGeometry(QtCore.QRect(83, 490, 5, 70))
        self.line_8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_8.setLineWidth(0)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.recapture_button = QtWidgets.QPushButton(Form)
        self.recapture_button.setGeometry(QtCore.QRect(860, 410, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana Pro Semibold")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.recapture_button.setFont(font)
        self.recapture_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))#type: ignore 
        self.recapture_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(112, 11, 239);\n"
"    color:white;\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:  rgb(112, 11, 239) ;\n"
"    color:white;\n"
"    border:1px solid rgba(0,0,0,0.3);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(66, 6, 144);\n"
"    color:white;\n"
"    border:1px solid rgba(0,0,0,0.3);\n"
"    border-radius:20px;\n"
"}")
        self.recapture_button.setObjectName("recapture_button")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(150, 570, 411, 51))
        self.label_7.setStyleSheet("QLabel{\n"
"    border:1px solid transparent;\n"
"    border-radius:20px;\n"
"    ;\n"
"    background-color: rgb(112, 11, 239);\n"
"}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.user_fullname_label = QtWidgets.QLabel(Form)
        self.user_fullname_label.setGeometry(QtCore.QRect(164, 575, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(16)
        self.user_fullname_label.setFont(font)
        self.user_fullname_label.setStyleSheet("color:white;")
        self.user_fullname_label.setAlignment(QtCore.Qt.AlignCenter)#type: ignore 
        self.user_fullname_label.setObjectName("user_fullname_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.email_lineedit.setPlaceholderText(_translate("Form", "Email"))
        self.pass_lineedit.setPlaceholderText(_translate("Form", "Password"))
        self.login_button.setText(_translate("Form", "Login"))
        self.recapture_button.setText(_translate("Form", "Recapture"))
        self.user_fullname_label.setText(_translate("Form", "Quliyev Elmir"))
import img_rc2


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
